name: hexagonal_grid_widget
description: A hex layout widget with infinite omniscroll and is highly customizable. It's extremely efficient as only the hex widgets that are viewable are rendered while all others are not.
version: 1.0.4
homepage: https://gitlab.com/jbeckman/hexagonal_grid_widget

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  after_layout: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
